default:
    iac:
        enabled: true
        pullRequest:
            auditMode: true
            commentOnlyHighAndCritical: false
            comments: false
        scan:
            autofix: false
            checkov: true
            checkovModuleDownload: false
            cloudformation: true
            dockerfile: false
            exceptions: []
            helm: true
            kubernetes: true
            kustomize: true
            opal: true
            terraform: false
            terraformPlan: false
            tfsec: true
    sca:
        enabled: true
        pullRequest:
            auditMode: true
            commentOnlyHighAndCritical: false
            comments: false
        scan:
            acf: false
            acfLocations: 5
            acfLocationsFull: []
            exceptions: []
            licenseDetection: true
            linesOfCode: true
            sast: true
            scr: true
            secret: true
            vulnEvaluation: true
